Rails.application.routes.draw do
  root 'home#index'
  get '/login', to: 'sessions#new'
  get '/authorize', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#index'
  get '/hot', to: 'hot#index'
  get '/new', to: 'new#index'
  get '/rising', to: 'rising#index'
  get '/controversial', to: 'controversial#index'
  get '/top', to: 'top#index'
  get '/gilded', to: 'gilded#index'
  get '/wiki', to: 'wiki#index'
  get '/promoted', to: 'promoted#index'
  get '/logout', to: 'sessions#destroy'
end
